steps:
   - name: 'gcr.io/cloud-builders/docker'
     args: ['build', '-t', 'gcr.io/$PROJECT_ID/discord-bot', '.']
   - name: 'gcr.io/cloud-builders/docker'
     args: ['push', 'gcr.io/$PROJECT_ID/discord-bot']
   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
     entrypoint: gcloud
     args:
     - 'run'
     - 'deploy'
     - 'discord-bot'
     - '--image'
     - 'gcr.io/$PROJECT_ID/discord-bot'
     - '--platform'
     - 'managed'
     - '--region'
     - 'us-central1'
     - '--allow-unauthenticated'
     - '--set-secrets'
     - 'DISCORD_BOT_TOKEN=discord_bot_token:latest,CHANNEL_ID=discord_channel_id:latest'
     - '--min-instances'
     - '1'
     - '--max-instances'
     - '1'